version: '3.8'

services:

  mongo-dan:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dan
    networks:
      - dan-db-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8027:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dan
      ME_CONFIG_MONGODB_URL: mongodb://root:dan@mongo-dan:27017/
    depends_on:
      - mongo-dan
    networks:
      - dan-db-network

networks:
  dan-db-network:
    driver: bridge
